/*
 * shim.c – Thin C shim providing stable JNA-callable symbols
 *          for encoding and decoding Omega Chess protocol messages.
 *
 * This file wraps the asn1c-generated encoder/decoder functions
 * with a simple byte-array interface that the Java NativeAsn1Codec
 * JNA wrapper can call.
 *
 * Build: compiled as part of libasn1omega (see Makefile).
 *
 * Encode flow:  XER XML → xer_decode → C struct → uper_encode → UPER bytes
 * Decode flow:  UPER bytes → uper_decode → C struct → xer_encode → XER XML
 */

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "asn_application.h"
#include "xer_decoder.h"
#include "xer_encoder.h"
#include "per_encoder.h"
#include "per_decoder.h"

/* PDU collection generated by asn1c -pdu=all */
extern asn_TYPE_descriptor_t *asn_pdu_collection[];

/*
 * Look up an asn_TYPE_descriptor_t by its ASN.1 type name
 * from the auto-generated pdu_collection array.
 */
static asn_TYPE_descriptor_t *find_type(const char *name) {
    int i;
    if (!name) return NULL;
    for (i = 0; asn_pdu_collection[i]; i++) {
        if (strcmp(asn_pdu_collection[i]->name, name) == 0)
            return asn_pdu_collection[i];
    }
    return NULL;
}

/* ------------------------------------------------------------------ */
/*  XER-encode callback: appends bytes to a growing buffer            */
/* ------------------------------------------------------------------ */

struct xer_buf {
    char  *data;
    size_t len;
    size_t cap;
};

static int xer_buf_cb(const void *buffer, size_t size, void *key) {
    struct xer_buf *xb = (struct xer_buf *)key;
    if (xb->len + size > xb->cap) {
        size_t newcap = (xb->cap == 0) ? 256 : xb->cap;
        while (newcap < xb->len + size)
            newcap *= 2;
        char *tmp = (char *)realloc(xb->data, newcap);
        if (!tmp) return -1;
        xb->data = tmp;
        xb->cap  = newcap;
    }
    memcpy(xb->data + xb->len, buffer, size);
    xb->len += size;
    return 0;
}

/*
 * Encode an XER XML byte buffer into UPER binary for the given PDU type.
 *
 * pduType  – ASN.1 type name, e.g. "LoginRequest"
 * xmlBytes – XER XML payload (UTF-8)
 * xmlLen   – length of xmlBytes
 * outLen   – (out) length of the returned UPER buffer in bytes
 *
 * Returns a malloc'd buffer containing the UPER-encoded bytes.
 * The caller must free the buffer with ocmsg_free().
 * Returns NULL on failure.
 */
void *ocmsg_xer_to_uper(const char *pduType,
                         const char *xmlBytes, int xmlLen,
                         int *outLen) {
    asn_TYPE_descriptor_t *td;
    void *structure = NULL;
    asn_dec_rval_t dr;
    void *uper_buf = NULL;
    ssize_t uper_len;

    if (outLen) *outLen = 0;

    td = find_type(pduType);
    if (!td) return NULL;

    /* Step 1: XER XML → in-memory C structure */
    dr = xer_decode(NULL, td, &structure, xmlBytes, (size_t)xmlLen);
    if (dr.code != RC_OK) {
        if (structure) ASN_STRUCT_FREE(*td, structure);
        return NULL;
    }

    /* Step 2: C structure → UPER binary */
    uper_len = uper_encode_to_new_buffer(td, NULL, structure, &uper_buf);
    ASN_STRUCT_FREE(*td, structure);

    if (uper_len < 0 || !uper_buf) {
        if (uper_buf) free(uper_buf);
        return NULL;
    }

    if (outLen) *outLen = (int)uper_len;
    return uper_buf;
}

/*
 * Decode a UPER binary buffer into XER XML for the given PDU type.
 *
 * pduType   – ASN.1 type name
 * uperBytes – UPER-encoded payload
 * uperLen   – length of uperBytes in bytes
 * outLen    – (out) length of the returned XER XML buffer
 *
 * Returns a malloc'd null-terminated buffer containing XER XML (UTF-8).
 * The caller must free the buffer with ocmsg_free().
 * Returns NULL on failure.
 */
char *ocmsg_uper_to_xer(const char *pduType,
                         const void *uperBytes, int uperLen,
                         int *outLen) {
    asn_TYPE_descriptor_t *td;
    void *structure = NULL;
    asn_dec_rval_t dr;
    asn_enc_rval_t er;
    struct xer_buf xb = {NULL, 0, 0};
    char *result;

    if (outLen) *outLen = 0;

    td = find_type(pduType);
    if (!td) return NULL;

    /* Step 1: UPER binary → in-memory C structure */
    dr = uper_decode_complete(NULL, td, &structure,
                              uperBytes, (size_t)uperLen);
    if (dr.code != RC_OK) {
        if (structure) ASN_STRUCT_FREE(*td, structure);
        return NULL;
    }

    /* Step 2: C structure → XER XML */
    er = xer_encode(td, structure, XER_F_CANONICAL, xer_buf_cb, &xb);
    ASN_STRUCT_FREE(*td, structure);

    if (er.encoded < 0) {
        free(xb.data);
        return NULL;
    }

    /* Null-terminate the XML string */
    result = (char *)realloc(xb.data, xb.len + 1);
    if (!result) {
        free(xb.data);
        return NULL;
    }
    result[xb.len] = '\0';

    if (outLen) *outLen = (int)xb.len;
    return result;
}

/*
 * Free a buffer returned by ocmsg_xer_to_uper or ocmsg_uper_to_xer.
 */
void ocmsg_free(void *ptr) {
    free(ptr);
}
